// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`

/// Analyses mono `samples` (floats in -1..1) recorded at `sample_rate` Hz.
///
/// Errors are returned as the voice-core message, which Dart receives as an
/// exception.
Future<VoiceReport> analyzeSamples({
  required List<double> samples,
  required int sampleRate,
}) => RustLib.instance.api.crateApiAnalysisAnalyzeSamples(
  samples: samples,
  sampleRate: sampleRate,
);

/// Measurements for one recording (mirror of `voice_core::VoiceReport`).
class VoiceReport {
  final double durationS;
  final int sampleRateHz;
  final double rmsDbfs;
  final double lufs;
  final double? f0MedianHz;
  final double voicedFraction;
  final int syllableCount;
  final double syllablesPerSecond;
  final int pauseCount;
  final double pauseTotalS;
  final double longestPauseS;
  final List<VoiceWarning> warnings;

  const VoiceReport({
    required this.durationS,
    required this.sampleRateHz,
    required this.rmsDbfs,
    required this.lufs,
    this.f0MedianHz,
    required this.voicedFraction,
    required this.syllableCount,
    required this.syllablesPerSecond,
    required this.pauseCount,
    required this.pauseTotalS,
    required this.longestPauseS,
    required this.warnings,
  });

  @override
  int get hashCode =>
      durationS.hashCode ^
      sampleRateHz.hashCode ^
      rmsDbfs.hashCode ^
      lufs.hashCode ^
      f0MedianHz.hashCode ^
      voicedFraction.hashCode ^
      syllableCount.hashCode ^
      syllablesPerSecond.hashCode ^
      pauseCount.hashCode ^
      pauseTotalS.hashCode ^
      longestPauseS.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceReport &&
          runtimeType == other.runtimeType &&
          durationS == other.durationS &&
          sampleRateHz == other.sampleRateHz &&
          rmsDbfs == other.rmsDbfs &&
          lufs == other.lufs &&
          f0MedianHz == other.f0MedianHz &&
          voicedFraction == other.voicedFraction &&
          syllableCount == other.syllableCount &&
          syllablesPerSecond == other.syllablesPerSecond &&
          pauseCount == other.pauseCount &&
          pauseTotalS == other.pauseTotalS &&
          longestPauseS == other.longestPauseS &&
          warnings == other.warnings;
}

/// Something that makes a recording's measurements less trustworthy.
enum VoiceWarning { tooShort, clipped, tooQuiet }
